// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzrUZsCQF5PzvtsphAGezrjwUaEU7K4hM',
    appId: '1:71675337893:web:396e4f01a3855bc0d0414c',
    messagingSenderId: '71675337893',
    projectId: 'todo-mobile-app-d8b8f',
    authDomain: 'todo-mobile-app-d8b8f.firebaseapp.com',
    storageBucket: 'todo-mobile-app-d8b8f.appspot.com',
    measurementId: 'G-HKNZNCKCWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrP_3NVVaJuuie46EI1Cij4ogMLRmjw30',
    appId: '1:71675337893:android:4b20d496ec484091d0414c',
    messagingSenderId: '71675337893',
    projectId: 'todo-mobile-app-d8b8f',
    storageBucket: 'todo-mobile-app-d8b8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBC4WZA_xt4AlsoDCzGDZKCOSCwFgcPM',
    appId: '1:71675337893:ios:5274a15648b29619d0414c',
    messagingSenderId: '71675337893',
    projectId: 'todo-mobile-app-d8b8f',
    storageBucket: 'todo-mobile-app-d8b8f.appspot.com',
    iosClientId: '71675337893-ql8p8hu0hmd67r2sbusoqusp4aju28ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBBC4WZA_xt4AlsoDCzGDZKCOSCwFgcPM',
    appId: '1:71675337893:ios:26bf440474389197d0414c',
    messagingSenderId: '71675337893',
    projectId: 'todo-mobile-app-d8b8f',
    storageBucket: 'todo-mobile-app-d8b8f.appspot.com',
    iosClientId: '71675337893-kv4b6nrglu81pe1f99j7kqkponoooakk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppCleanArchitecture.RunnerTests',
  );
}
